services:
  #db:
  #  image: postgres:10
  #  environment:
  #    POSTGRES_DB: "grow"
  #    POSTGRES_USER: "sativa"
  #    POSTGRES_PASSWORD: "sativa"
  #  ports:
  #    - "5432"
  cache:
    container_name: cache
    image: redis:6
    networks:
      - directus

  directus:
    container_name: directus
    image: directus/directus:latest
    ports:
      - 8055:8055
    volumes:
      # By default, uploads are stored in /directus/uploads
      # Always make sure your volumes matches the storage root when using
      # local driver
      - ./uploads:/directus/uploads
      # Make sure to also mount the volume when using SQLite
      # - ./database:/directus/database
      # If you want to load extensions from the host
      # - ./extensions:/directus/extensions
    networks:
      - directus
    depends_on:
      - cache
    env_file:
      - "./backend/centralAPI/.env"

      # Make sure to set this in production
      # (see https://docs.directus.io/self-hosted/config-options#general)
      # PUBLIC_URL: 'https://directus.example.com'
      
  central_api:
    build: ./backend/centralAPI
    ports:
      - "3001:3001"
    volumes:
      - "./backend/centralAPI/api:/src/api"
    env_file:
      - "./backend/centralAPI/.env"
    #depends_on:
    #  - db

  
      
  client:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - "./frontend/public:/app/public"
      - "./frontend/src:/app/src"
    env_file:
    - "./frontend/.env"
    - "./frontend/.env.local"
networks:
  directus: